version: "3"

services:
  elasticsearch:
    image: lenic/elasticsearch-oss:6.2.4
    ports:
      - 9200:9200
      - 9300:9200

  kibana:
    image: lenic/kibana-oss:6.2.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    image: lenic/logstash-oss:6.2.4
    depends_on:
      - elasticsearch
    volumes:
      - ./yaml/logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  filebeat:
    image: lenic/filebeat:6.2.4
    depends_on:
      - logstash
    volumes:
      - ./yaml/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/home/logs/
