version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ports:
      - 9200:9200
      - 9300:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:6.1.1
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - ./yaml/logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.1.1
    links:
      - logstash
    depends_on:
      - logstash
    volumes:
      - ./yaml/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/home/logs/
